### PR TITLE
Add Vagrant config

### PR DESCRIPTION
**Pull request by PiDelport**
This addresses issue #28.

See the README instructions: this should hopefully be enough for folks to get a Buza instance running with `vagrant up`.

### CODE REVIEW

**Review by sewagodimo — APPROVED** [review]
I will only be able to try and set it up tonight but it looks good @pjdelport 
I am happy for you to merge it!
:cake: :beer:

**Comment by PiDelport** [comment]
@sewagodimo: I'm happy to wait until you test it! I'd rather have at least one other person get this Vagrant setup working before merging it. :)

**Comment by PiDelport** [comment]
Cool, I think this should actually be ready now!

**Comment by PiDelport** [comment]
Closes #28.

**Pull request merged**
